### PR TITLE
trying again with the correct relative path for assets

### PR DESCRIPTION
**Pull request by dzygmundfelt**

### CODE REVIEW

**Comment by dzygmundfelt** [comment]
@hawc2 this is still a draft, so don't merge it in. I ran locally and the images showed up correctly but the markdown preview in github isn't picking them up, so maybe it's still no good.

**Comment by dzygmundfelt** [comment]
F. https://github.com/mkdocs/mkdocs/issues/292

**Comment by dzygmundfelt** [comment]
May be related to https://github.com/mkdocs/mkdocs/issues/292

**Comment by dzygmundfelt** [comment]
This approach will maybe mean that the images are broken in github's markdown rendering but not on the actual site. I'll bring this up tomorrow at the tech meeting but it might be worthwhile to just try merging this change in.

**Comment by hawc2** [comment]
unfortunately the images still aren't rendering right @dzygmundfelt, not sure what the problem is. @addiebarron any ideas why this isn't working?

**Pull request merged**
