### PR TITLE
8-22 Updates

### PR DESCRIPTION
**Pull request by eugenethreat**
* Add device troubleshooting page for APs and ERX
    * Added troubleshooting/fixes for Isolated APs  
    * Added section on AP LED status indicators 
* Add content to `buildingassessment.md`
* Revise hardware list 
* Updated software list to remove unused resources
* Added `airmonitor` page
* added `IoT Devices` page 
* Added connection sharing instructions for Windows
* Added 'mesh overview' page 
    * Added new photo of wall mesh AP
* Revised 'PhillyWisper' to include link to page on refs. 
* Added 'useful commands' page 
* Add blurb on DHCP, SSH, and removed references to firmware version 4.3.2 from `configure-ap-mesh`
* moved photos into subfolders based off of page they occur on, following site structure 
    * `assets/images/device-configs/`erx`` ... etc

### CODE REVIEW

**Comment by hawc2** [comment]
@eugenethreat looks like the image for ssh in the mesh ap guide isn't rendering right.

One other minor thing is we do have a section for air monitors on the website. Maybe the content there should be moved to our docs, or vice versa?

Otherwise, looks great!

I'll do line edits at some later point, just checking for basic functionality for now

**Comment by eugenethreat** [comment]
> @eugenethreat looks like the image for ssh in the mesh ap guide isn't rendering right.
Fixed! The other 3 images here weren't rendering correctly as well.

> One other minor thing is we do have a section for air monitors on the website. Maybe the content there should be moved to our docs, or vice versa?
I believe it's not being linked anywhere - I'd be fine either way, especially once we compress the navbar. 

image

**Comment by hawc2** [comment]
@eugenethreat for now let's delete the webpage for airmonitors on our site, there's almost nothing there anyway. for now, let's put it on our docs to have internal info on what we're doing, and then we can later make it a part of our marketing and public profile on the website once we've thought it out more. 

one thing it would be nice to see on the docs for airmonitors is a screenshot of the purple air map in our coverage area with a date listed for when it was taken, so people can see the monitors we've installed. we could keep updating over time

**Comment by eugenethreat** [comment]
> @eugenethreat for now let's delete the webpage for airmonitors on our site, there's almost nothing there anyway. for now, let's put it on our docs to have internal info on what we're doing, and then we can later make it a part of our marketing and public profile on the website once we've thought it out more.

Moved content from `airmonitors.md` on website to airmonitor page on this side 

> one thing it would be nice to see on the docs for airmonitors is a screenshot of the purple air map in our coverage area with a date listed for when it was taken, so people can see the monitors we've installed. we could keep updating over time

I'll do you one better - added an iframe linked to the live map

**Comment by hawc2** [comment]
Great thanks, feel free to merge this then!

**Pull request merged**
